[project]
name = "gen-cli"
version = "1.1.0"
description = "A CLI tool to generate boilerplate code and framework templates for multiple programming languages."
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
keywords = ["boilerplate", "generator", "cli", "templates", "scaffold"]

authors = [{ name = "Prasad Raju G" }]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Code Generators",
]

dependencies = ["Jinja2>=3.1.6"]

[project.urls]
Homepage = "https://github.com/iamprasadraju/gen-cli"
Repository = "https://github.com/iamprasadraju/gen-cli"
Issues = "https://github.com/iamprasadraju/gen-cli/issues"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project.scripts]
gen = "gen.cli:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
gen = ["templates/**/*"]

# for the devs
[project.optional-dependencies]
dev = [
    "pylint>=3.3.8",
    "black>=25.9.0",
    "isort>=6.1.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
]